name: ci
on:
  push:
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/Makefile') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true
      - name: Build and lint
        run: |
          make
  breaking:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1.32.0-beta.1
        with:
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: https://github.com/bufbuild/confluent-proto.git#branch=main
